excluded:
  - .build
  - DerivedData
  - AuralystAppUITests

disabled_rules:
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - large_tuple
  - trailing_comma
  - nesting
  - cyclomatic_complexity
  - force_cast
  - force_try
  - multiple_closures_with_trailing_closure
  - trailing_newline

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_filter_count
  - multiline_arguments
  - vertical_whitespace_closing_braces

line_length:
  warning: 180
  error: 250
  ignores_comments: true
  ignores_urls: true
