excluded:
  - .build
  - DerivedData
  - .derivedData

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_filter_count

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - db
    - id
    - lh
    - rh

line_length:
  ignores_comments: true
  ignores_urls: true
